### ISSUE TITLE
elive-browser-on-ram missing 'brave-browser'

### ISSUE THREAD

**Issue by triantares** [Elive/elive-daemons#2]
Not my personal choice but 'brave-browser' should be defined in the choices list too IMO

**Comment by Thanatermesis** [comment]
Elive has a GUI for the user, but the tool itself doesn't support brave-browser if I'm not wrong, so this should be reported first to the original project and make them to implement it: https://github.com/graysky2/profile-sync-daemon

note that if they do, this means elive needs to create an own package for it instead of using the version from debian (or wait that debian updates it)

**Comment by Thanatermesis** [comment]
also check:  https://github.com/graysky2/profile-sync-daemon/issues/304
